export const ABOUT_INFO_LOADING = 'ABOUT_INFO_LOADING';
export const ABOUT_INFO_FAILED = 'ABOUT_INFO_FAILED';
export const ADD_ABOUT_INFO = 'ADD_ABOUT_INFO';

export const PIZZA_LOADING = 'PIZZA_LOADING';
export const PIZZA_FAILED = 'PIZZA_FAILED';
export const ADD_PIZZA = 'ADD_PIZZA';

export const SALADS_LOADING = 'SALADS_LOADING';
export const SALADS_FAILED = 'SALADS_FAILED';
export const ADD_SALADS = 'ADD_SALADS';

export const STARTERS_LOADING = 'STARTERS_LOADING';
export const STARTERS_FAILED = 'STARTERS_FAILED';
export const ADD_STARTERS = 'ADD_STARTERS';

export const TOPPINGS_LOADING = 'TOPPINGS_LOADING';
export const TOPPINGS_FAILED = 'TOPPINGS_FAILED';
export const ADD_TOPPINGS = 'ADD_TOPPINGS';

